[Video MD5 support] PR 3/3:  (#749)
* [hma] hmalib.ContentType enum replaced with threatexchange.ContentType classes

HMA should be able to immediately benefit from improvements to threatexchange. ThreatExchange already has ContentType and SignalType abstractions. Building off of those, replace all ContentType references in hma with the corresponding threatexchange classes.

* [hma] Add ContentType to URL submission requests

Instead of writing additional conditionals every time we want to support a new content type, make the submission message (for URLs) generic. It will support all content_types.

For brevity, this commit does not include all of this refactor. pdq_hasher must have changes to support the new submission messages, but they are removed in the next commits. URL Submissions messages are now supported by a unified lambda for all content types.

* [hma] Webapp supports explicit content type

First, map ContentType enum to threatexchange.ContentType subclasses rather than hmalib content types.

Second, switch over string usage to enum usage wherever hard-coded.

* [hma] Rename image_sources to content_sources

They are capable of fetching bytes from URLs. Nothing fundamentally image specific about them.

Apologies. Some of the refactor for this also bleeds over into the next commit. Specifically, `pdq_hasher.py`

* [hma] Add generic hasher which can handle any content and signal types; route submissions to it via a different SQS queue

As part of this, pdq_hasher.py's capability to handle URL only submissions is also being moved to the generic hasher. Once this diff lands, only S3 based submissions will go to pdq_hasher.

Also sets up terraform infrastructure.
- New SQS queue for URL submissions. Soon to include all submissions.

Does not yet publish matches, only prints them to logger. That will require generic-ifying matcher first.

Includes some pending refactors from previous commits. in submit.py and pdq_hasher.py. `URLImageSubmissionMessage` -> `URLSubmissionMessage` and `ImageSource` -> `ContentSource`.

`setup.py`: [tiny] so far, we were depending on threatexchange to provide requests implicitly. Made that explicit

* Review feedback and test fixes

* [script] helper for creating multi-part pull requests

Have now done this enough number of times to warrant automating.

* [md5-fetcher] Fetch indicators of type MD5 in fetcher.py

* Move ThreatUpdateS3Store to s3_adapters.py

There is potential for re-use of the same class between indexer, matcher and fetcher. Having a single place for everything to do with signal storage makes refactors easier.

* Call ThreatUpdateS3Store.supported_indicator_types only once

* Squash of index-md5 branch (#732), includes all commits of #725

commit 269347dffc75128bf0b4e92caaef2448d3086a6f
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:34:42 2021 +0000

    terraform the unified indexer; remove pdq_indexer

commit 018fbf91b56fbf31f70524476bdfac90e17d7da3
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:34:20 2021 +0000

    Add a unified indexer lambda that will index all supported indicator types from threatexchange

    At this point:
    PDQ and MD5. But easily extendable to more.

commit 52454482fd81085d368d7aeec5da70526c253a73
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:33:07 2021 +0000

    Encapsulate index saving / loading into dedicated module

commit dcc7e8e531440c30a12967fce1dc6c540e9feee2
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:32:06 2021 +0000

    Internalize signal_type to datafile key in s3_adapters

    Also provide a reversing function to test whether an s3 key provides threatexchange data.

commit 7bfddb36ce0622002dbdb563314a43ca283db18e
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Fri Jul 23 20:46:15 2021 +0000

    Move ThreatUpdateS3Store to s3_adapters.py

    There is potential for re-use of the same class between indexer, matcher and fetcher. Having a single place for everything to do with signal storage makes refactors easier.

commit bdab484a301b6028b06a29ce320da1bc787bd4b5
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Fri Jul 23 20:27:43 2021 +0000

    [md5-fetcher] Fetch indicators of type MD5 in fetcher.py

commit ae27fb314de4415a2931cdbeb8255ebe36fdc687
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Wed Jul 21 13:54:11 2021 -0400

    [threatexchange][hotfix] Missing function invocation in `threatexchange.content_type.meta.get_content_type_for_name` (#724)

    Summary
    ---
    Also bumps version to 0.0.22. 0.0.21 should be considered poisoned.

    Test Plan
    ---
    ```
    >>> from threatexchange.content_type.meta import get_content_type_for_name
    >>> get_content_type_for_name('photo')
    ```

    Before

    ```
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/content_type/meta.py", line 53, in get_content_type_for_name
        return _get_content_type_map[name]
    TypeError: 'functools._lru_cache_wrapper' object is not subscriptable
    ```

    After

    ```
    <class 'threatexchange.content_type.photo.PhotoContent'>
    ```

* SignalValue → ContentSignal; have it encapsulate the content and signal details

To be able to pass it along to other systems, the object must have content_id and content_type

* Extract SignalType → Index class mapping to a common module

This allows the mapping to be re-used in matchers.

* Extract DynamoDB test setup into a dedicated module

* Make Hash and Match records signal-type agnostic

- PipelinePDQHashRecord and PDQMatchRecord were converted into their signal_type agnostic variants: PipelineHashRecord and MatchRecord respectively.
- Since the record classes themselves are signal_type agnostic, the HashRecordQuery and MatchRecordQuery classes were dissolved and their methods integrated into the Record classes directly.
- from_time_range queries and scans were removed in favour of get_recent_items queries which uses the LastEvaluatedKey from LIMITed queries to acheive performant pagination.

  As part of this, the "GSI2-PK" now uses the Record class name instead of the signal_type, so you have type#PipelineHashRecord instead of type#pdq. This allows using the same index for indexing hash, match (and potentially other) records.
- PipelineHashRecord.from_content_id now returns a list because the whole point of this branch is to support 1:many content:signal mapping.
- **signal_specific_attributes**: to allow hash and match records to be queried and written in a unified manner, the signal_type specific pecularities of these records are being abstracted into a bag of attributes. This bag of attributes is flattened out when writing so that we can create indexes later if required. (only top-level attributes can be indexed in ddb.)
- SignalType top level attribute in hash match records. Allows for explicit types instead of relying on SK string transform. This was also added to both GSIs.
- model tests now use the new ddb_test_common module for doing common ddb mocking.
- PipelineHashRecord and MatchRecord call-sites were updated to use new APIs. They have not been tested however. That will be done at branch tip.

* minor: add logging to webhooks

* ui: Support video when uploading media

* Moved hasher terraform configuration into its own module

* Add all fields to PipelineHashRecord sqs_message;

- write hash_records and publish_message when hashing using unified_hasher

* Add signal agnostic matcher

* minor-bug: Correct type when querying image bytes

* Oops, only publish match message if there are matches

* Address review feedback from @barrett on #749

- Expanded doc string on hmalib.common.mappings
- forward and backward docs on datastore/main.tf and test_pipeline_models to keep them in sync
- moved test_pdq_models to test_pipeline_models
- added md5 centric test cases to test_pipeline_models
- docstring for to_legacy_sqs_message in PipelineHashRecord
- add TODO to extract signal record keeping functionality in write_signal_if_not_found
- note in docstring that Matcer.match also filters matches from inactive datasets

* oops: merge conflict resolution was not perfect

* misc fixes after merge conflict resolution