better error message for uninitialized (#514)
Summary
---------

Quick improvement for those now seeing uninitialized asserts

Test Plan
---------

```
>>> HMAConfig.get("a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dcallies\github\fork-ThreatExchange\hasher-matcher-actioner\hmalib\common\config.py", line 92, in get
    _assert_initialized()
  File "C:\Users\dcallies\github\fork-ThreatExchange\hasher-matcher-actioner\hmalib\common\config.py", line 30, in _assert_initialized
    assert _TABLE_NAME, """
AssertionError: HMAConfig.initialize() hasn't been called yet with the config table.
If you are writing a new lambda, make sure you initialize in the entry point,
likely passing in the table name via environment variable.

>>> HMAConfig.initialize("a")
>>> HMAConfig.initialize("a")
>>> HMAConfig.initialize("b")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dcallies\github\fork-ThreatExchange\hasher-matcher-actioner\hmalib\common\config.py", line 145, in initialize
    assert _TABLE_NAME in (
AssertionError: HMAConfig was already initialized with a!
```